### ISSUE TITLE
Not working for prod

### ISSUE THREAD

**Issue by jannikbuscha** [Zeng95/vue-airbnb-ssr#2]
hey, really cool project, it really helped me. However, I have a problem in prod. if I build the project with `build:ssr` and start it on a server with `prod:ssr`, then the axios requests no longer work with the proxy.

The requests are displayed in the network tab but the response is simply the `index.html`:
![image](https://user-images.githubusercontent.com/74017697/176947238-f909510d-bb2c-448a-a47d-111a0be0d1af.png)

Could it be because I don't use a router? I have removed everything that has to do with routers. However, everything works locally with `dev:ssr`.

My `package.json` scripts:
```json
"dev:ssr": "cross-env NODE_ENV=development npx node-dev server",
"prod:ssr": "cross-env NODE_ENV=production npx node-dev server",
"build:ssr": "npm run build:client && npm run build:server",
"build:client": "vite build --ssrManifest --outDir dist/client",
"build:server": "vite build --ssr src/entry-server.js --outDir dist/server",
```

My `vite.config.ts`:
```ts
import {fileURLToPath, URL} from 'url'

import {defineConfig, loadEnv} from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig(({ command, mode }) => {
    const env = loadEnv(mode, process.cwd())

    return {
        plugins: [vue()],
        resolve: {
            alias: {
                '@': fileURLToPath(new URL('./src', import.meta.url))
            }
        },
        server: {
            proxy: {
                "/api": {
                    target: `https://${env.VITE_DASHBOARD_SUB}.${env.VITE_DOMAIN}`,
                    changeOrigin: true
                },
                "/tebex": {
                    target: "https://plugin.tebex.io",
                    changeOrigin: true,
                    rewrite: (path) => path.replace(/^\/tebex/, ""),
                    headers: {
                        'X-Tebex-Secret': env.VITE_TEBEX_SECRET
                    }
                }
            }
        },
        css: {
            preprocessorOptions: {
                scss: {
                    quietDeps: true,
                    additionalData: `
                    @use 'aos/dist/aos.css';
                    @use 'sweetalert2/src/sweetalert2.scss';
                    @use '@/assets/scss/sweetalert.scss';
                    @use '@/assets/scss/fonts.scss';
                    @use '@/assets/scss/slides/slides.scss';
                `
                }
            }
        }
    }
})
```

**Comment by leotaozeng** [comment]
1. Make sure you set Axios config option `baseURL` for production 
2. Move your prefix "/tebex" for only development

Example below:

```js
const defaultsConfig = {
  baseURL: import.meta.env.DEV
    ? 'http://localhost:9000/proxy'
    : 'http://110.42.184.111',
};
```

You can check the branch [fix/axios-config](https://github.com/Zeng95/vue-airbnb-ssr/tree/fix/axios-config)

**Comment by jannikbuscha** [comment]
> 1. Make sure you set Axios config option `baseURL` for production
> 2. Move your prefix "/tebex" for only development
> 
> Example below:
> 
> ```js
> const defaultsConfig = {
>   baseURL: import.meta.env.DEV
>     ? 'http://localhost:9000/proxy'
>     : 'http://110.42.184.111',
> };
> ```
> 
> You can check the branch [fix/axios-config](https://github.com/Zeng95/vue-airbnb-ssr/tree/fix/axios-config)

thanks!
